# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TellMeAMovie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TellMeAMovie
  pod "TMDBSwift"
  pod 'SDWebImage', '~>3.8'
  pod 'YSRangeSlider'
  pod 'RealmSwift'
  pod 'PureLayout'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # or '2.3'
    end
  end
end
